name: Example Workflow
on: [push]

jobs:
  build:
    greeting:
      runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      uses: actions/bin/filter@v1
      with:
        args: echo "Hello from Github Actions! :wave:"

    - name: Notify Slack
      uses: slack-actions/slack-message@v1
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        args: ${{ toJson(steps.send-greeting.outputs) }}
      
