name: Example Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: slack-send
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
       with:
        # This data can be any valid JSON from a previous step in the GitHub Action
        payload: 
          {
            "username": "id",
          }

